language: python
python: 3.6
install:
#- pip install -r requirements/dev.txt
#- pip install codecov
script:
- ls
#- python -m unittest discover
#- coverage erase
#- coverage run --source=ChangePop test_webapp.py
#- coverage html
after_success:
#- codecov
branches:
  only:
  - master
  - develop
  - deploying-azure
deploy:
  - provider: azure_web_apps
    username: deploy_user_az
    password: faa5scSeR7
    site: Kalepa       # If AZURE_WA_SITE isn't set
    #slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
    verbose: true
    on: deploying-azure