language: python

python: 3.6

install:
- pip install -r requirements/dev.txt
- pip install codecov

script:
- python -m unittest discover
- coverage erase
- coverage run --source=ChangePop test_webapp.py
- ls
- coverage html

after_success:
- codecov

branches:
  only:
  - master
  - develop
  
deploy:
  - provider: heroku
    api_key:
      secure: TlBK8NNyK29lUSgPtNH96tJZPNSIRPvFBDb8pEN+dhOdHgKl85aaCo1t1gN5e0eXPVwWA7HHA8uFWhHCxpOkwLrZs2DQk3FbOxa5Det130m3zqtW8NlsBzzIxsuu30irTAJ2bbVqc63jOoY32XkJX1N9qUZAF3gtc5wqoqIP0HaR3a+vh/yFOhnFWORmrH/9JoR3d0R7nDCO8cGX74BZQ3OhAY+4ZIkdlwtfO7upNpfgREdKKcJAyFBB2w3FOoP+npQNm/qckJgusMrnsbuVEl2u4MKnQTgKfGAsNBJvI0mEnEEyYAX35Kh9OTrvBLJddD0K8ELbB9/l60YgLVzhRWMtGyt+ivSrSGB/o+yEJaL3aJs271IQrtdZfwFjvct4BmGInDKLVuNbi9hFm30EzHc5NzPu592Xp2Ab4kfQ/PvfLhGlQs13lxyCLcfiUKrBcBMoLl3q4S0RRlrQ2VlGJfZw2DlUkxfSSd36nXcOocE4l9mkyCafw0jhW0tuFd/JOqoXsvCKFJJEtBdyqH/CMfGHuo3eZ/M5p1YIJppmlZfeDIHyVSAKogh1+4Lw9qyNRcQ/qcTFBOi7eR9qBOUorw7z+9tAiE4ChQIDqvgsYVhHoOkxeW+r/ckyWM1Sv6RfBLLh26as7QkmniSAz9yLFCg/Bf/0SKPmMJNj6CxL7zI=
    app: kelpa-api
    on:
      python: 3.6
      branch: master