language: python
python: 3.6
install:
- pip install -r requirements/dev.txt
- pip install codecov
script:
- python -m unittest discover
- coverage erase
- coverage run --source=ChangePop test_webapp.py
- coverage html
after_success:
- codecov
branches:
  only:
  - master
  - develop
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: HWsUtnBVC8D5YcWcEQsSgUstCc4Y6eXT6Rjivu+UUUw8GzX4/u6goeMIU2wsDH8+uKZGbiQh5Ol4IIudynkicDfy89H8v3NIUAA3mE7AFekmB8NhqmIuLOhWjt6zRgsUm7fCx4t6UNgpYI/wqG5wAM1EMvEwsa+YGdhddz+DFlH1KUi2WtdGx69OX9IUKx+xxIw8UJ/PeMOJ5cdC1tj3RVTfss5TmEqT4UmrEgF1JzNmjPn8iWhlywe8XAifQV9XVui5hzgNHOnxodUIQq40Ro3HjBXFJwTem8Gg1DCPvTiT8n9Y5MvmzwQaAWVNJAz+d20x3CnLt1OZYYhlVbYbjU5sExoqIP3l/sNBdXoZ4U94greWvgwBPRQP33zXzk1vI3ywmGWyZVNxWUFf8Ln7f4JnKAYgXax8l0W03MgUrts+zYgLnHgbmMa+HD0AYVjfx24PEni5PdaapJLrgpwuecncGjgn/cCt4cck3tNRggiiCzxECwiyke8DcKFSSx0sjqWwl+AHKxyWhUmMEGVhDdJseLDpNcbeOqZWTyUKF2ndzowo60nVUnLEzlU1UjeDyfYahCE+hVUCFecbTXwjSQ9KOZ/xLwCJJxCz9loSkNMFQXBfQ2fIkmsff+TmFUeoz/mHCbawf4geVcFpEMoTXWF24RXippUZ+5sspYA+FQk=
    app: kelpa-api
    on:
      python: 3.6
      branch: master
  