language: python
python: 3.6
install:
- pip install -r requirements/dev.txt
- pip install codecov
script:
- python -m unittest discover
- coverage erase
- coverage run --source=ChangePop test_webapp.py
- coverage html
after_success:
- codecov
branches:
  only:
  - master
  - develop
deploy:
  - provider: heroku
    api_key:
        secure: T7TlHhIzTLNNBI6xL2mog5vRt1ghowTmjG5nyi09uPKDMBmSxoKJXhGWmZwwQUsZ53/p+T00B3ZoBzwv0Upn5fcGdJGD/lEUIPq1vUVlPb3uYw+Xc3cPs2Vjsi4jXcGGE8mOT+J4+kHN0a5IIS/WhcmFM5dHMinGO4CmUtDW0rJX2rTboZkeaQGjwWI2nq966WJrVyKUxlIom1PwEfzu3wMRS6BF2mxumohSAWtL0ZlzUmBMup9MW7rhenaPpkCSqi9OKJBxWcJkWnKydgXG35rNsIOcnGBY2h5UnJ8sXVGh+Lq5c5tjMnhkr6AQEWdKQgoPM9C/sDYfDajyLPcolMVRUW/OGIM64d4k0asi06ibbA8KMrQ7o5qyrLZmA4z8dRIdb1LDV6VAqs9rUtqanoAHcRtNoVq+7kWs3UotxfyHVD/o0xLQWH7Ab4vLelXfSTcaqY+C2tJdRPaYqCV2BuZyZg/cErxTxALQz81QeSWggifGmg8P39CPCX1ChFA1GmqdmEkuyxJiNYbNCdejTvKJn6CbHZXtCm2QgscUCxaOu/+KEjFLbEL3yqBtgLANoueYmLuHhgOzxX2ecZJ6jdnq6to5kILxID7imInFve0iuJUZRwGC1SKfKMXe5e0IpIMmeHvfqyBpSxJwaWnTlJVNoVmYe4xuKc6mbv3UfGk=
    app: kelpa-api
    on:
      python: 3.6
      branch: master
