language: python

python: 3.6

install:
- pip install -r requirements/dev.txt
- pip install codecov

script:
- python -m unittest discover
- coverage erase
- coverage run --source=ChangePop test_webapp.py
- coverage html

after_success:
- codecov

branches:
  only:
  - master
  - develop
  
deploy:
- provider: heroku
  api_key:
    secure: SInyWw+8A/2p455wUzyhZZGStObcUvTR0ge4NDAOjo1V2wgsmoPk+601ldYqEZHGWCCeUNg2PZ2yg6f6EWvrz71k2lOnILXGH6y4+PWJzdfCxcEcN+DsGs0R8RkR7WtESUTv3mjwF9p08A5IQn4FyNVxSbs90/Wafl9FsMCP4bXS8/5qkau7hvHICbZntw/3gtN+UM7TuQcrgJmxdvzP+xzk1nQP89bSZyW6ZvtlbKUHGNNM1J4LZD0waQVksN03g7s5hF38zRQCOaDXl0gg5+Y6BwAyj8uGTs6IqCMeSS/PqJH1WUG8o9OEkEP6V8p29PlEFy08nZPBq9LwG/IV2gromXuer4dEw+bCoz/Uuz0g0SQfVtJK5QzJU04I9FhKatnzOKAm5dJiJA+JffrsKyN2cacj1Sxf6yrNMAQtRpqJ2HL1TnYRLRBOmQx0XqV0gE0p9YAa7lMy3oY+arsHa0uZXNoV0sfVpIzhJGrTz/ieyEkw9ebbRbXWXA+WlBL+10tPq6Bp68zAd5UYf08MecXMzqpe7C8k528Eav+ZVKRZifiMlAdSAZ9PQeaJKvrJAqYAFMpjx98b/LOUzZvRXiPakBAuVWgFcoS8bvcFm72Pj3hj803AE0bt0eHZrCY+ArQVI2y6HrOrIxBVrVMJXtuMhIaL3oSlEj0ed5v0RcA="
  app: kelpa-api
  on:
    python: 3.6
    branch: master
      